name: Repo Dispatch Example

on:
  repository_dispatch:
    types:
      - my-event

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print simple message
        run: echo "Repository dispatch received"